/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial.pkg2;

import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author 54364
 */
public class FrmPrinicipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrinicipal
     */
    public FrmPrinicipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ejercicio 1");

        jButton2.setText("Ejercicio 2 ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ejercicio 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ejerccio 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ejercicio 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Especialidad radiologia = new Especialidad(191, "Radiología");
        Profesional medico1 = new Profesional("Juan", "Perez", 40, true, radiologia, "Maria");
        Pasiente pasiente1 = new Pasiente("Maria", "Gomez", 70, true, "123456", "INSSSEP");
         Clinica clinica = new Clinica();
      
        
       

        List<Pasiente> pacientesMartesCardiologia = clinica.listarPacienteMartesRadiologia();
        
        // Ahora puedes mostrar la lista de pacientes en un JOptionPane o en otro componente de la GUI
        String mensaje = "Pacientes en Cardiología el Martes 12 de septiembre de 2023:\n";
        for (Pasiente paciente : pacientesMartesCardiologia) {
            mensaje += paciente.getNombre() + "\n";
        }
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Clinica   clinica= new Clinica();
        // Obtener la cantidad de camas de una plaza y televisores
        int cantidadCamasUnaPlaza = clinica.getCantidadCamasUnaPlaza();
        int cantidadTelevisores = clinica.getCantidadTelevisores();
        
        // Construir el mensaje con la cantidad de recursos
        String mensaje = "Cantidad de recursos:\n";
        mensaje += "  - Camas de una plaza: " + cantidadCamasUnaPlaza + "\n";
        mensaje += "  - Televisores: " + cantidadTelevisores + "\n";
        
        // Mostrar el mensaje en un cuadro de diálogo
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Clinica clinica = new Clinica();
         // Obtener la lista de turnos por profesional y especialidad
        Map<Profesional, Map<Especialidad, List<Turnos>>> turnosPorProfesionalEspecialidad = clinica.listarTurnosPorProfesionalEspecialidad();
        
        // Recorrer el mapa y mostrar los turnos
        StringBuilder mensaje = new StringBuilder("Turnos por Profesional y Especialidad:\n");
        for (Map.Entry<Profesional, Map<Especialidad, List<Turnos>>> entryProfesional : turnosPorProfesionalEspecialidad.entrySet()) {
            Profesional profesional = entryProfesional.getKey();
            mensaje.append(profesional.getNombre()).append(":\n");
            
            Map<Especialidad, List<Turnos>> turnosPorEspecialidad = entryProfesional.getValue();
            for (Map.Entry<Especialidad, List<Turnos>> entryEspecialidad : turnosPorEspecialidad.entrySet()) {
                Especialidad especialidad = entryEspecialidad.getKey();
                List<Turnos> turnos = entryEspecialidad.getValue();
                
                mensaje.append("  ").append(especialidad.getNombre()).append(":\n");
                for (Turnos turno : turnos) {
                    mensaje.append("    - ").append(turno.getPaciente().getNombre()).append("\n");
                }
            }
        }
        
        // Mostrar el mensaje en un cuadro de diálogo
        JOptionPane.showMessageDialog(null, mensaje.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Clinica clinica = new Clinica();
         // Obtener la lista de pacientes mayores de 65 años afiliados a INSSSEP
        List<Pasiente> pacientesMayores65INSSSEP = clinica.listarPacientesMayores65AfiliadosINSSSEP();
        
        // Construir el mensaje con la lista de pacientes
        StringBuilder mensaje = new StringBuilder("Pacientes mayores de 65 años afiliados a INSSSEP:\n");
        for (Pasiente paciente : pacientesMayores65INSSSEP) {
            mensaje.append("  - ").append(paciente.getNombre()).append("\n");
        }
        
        // Mostrar el mensaje en un cuadro 
        JOptionPane.showMessageDialog(null, mensaje.toString());
    
    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrinicipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
